services:
    mysql8-service:
        image: 'mysql:8.0'
        container_name: mysql8-container
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: secret_db
        ports:
            - '3306:3306'
        restart: always
