services:
    mariadb-service:
        image: 'mariadb:10.11'
        container_name: mariadb-container
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: secret_db
        ports:
            - '3306:3306'
        restart: always
